# Generated by Django 6.0.1 on 2026-01-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название игры')),
                ('image', models.ImageField(upload_to='games/', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('memory', models.FloatField(verbose_name='Размер памяти (ГБ)')),
                ('platform', models.CharField(choices=[('PC', 'PC'), ('PS', 'PlayStation'), ('Xbox', 'Xbox'), ('Switch', 'Nintendo Switch'), ('Mobile', 'Mobile')], max_length=20, verbose_name='Платформа')),
                ('category', models.CharField(choices=[('Action', 'Action'), ('RPG', 'RPG'), ('Strategy', 'Strategy'), ('Adventure', 'Adventure'), ('Sports', 'Sports'), ('Racing', 'Racing'), ('Puzzle', 'Puzzle'), ('Simulation', 'Simulation'), ('Horror', 'Horror'), ('MMO', 'MMO')], max_length=20, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['-created_at'],
            },
        ),
    ]
